# Generated by Django 5.2.15 on 2026-06-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ISBN')),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('author', models.CharField(max_length=200, verbose_name='作者')),
                ('publish_date', models.DateField(verbose_name='出版时间')),
                ('publisher', models.CharField(max_length=200, verbose_name='出版社')),
                ('introduction', models.TextField(blank=True, verbose_name='简介')),
                ('catalog', models.TextField(blank=True, verbose_name='目录')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
                'ordering': ['-publish_date'],
            },
        ),
    ]
